# Generated by Django 5.1.1 on 2024-09-18 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='patient',
            name='outcome',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
