# Generated by Django 5.1.1 on 2024-09-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rename_outcome_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='case',
            name='treatment',
        ),
        migrations.AddField(
            model_name='case',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='cases.symptom'),
        ),
        migrations.AddField(
            model_name='case',
            name='treatment',
            field=models.ManyToManyField(blank=True, to='cases.treatment'),
        ),
    ]
