# Generated by Django 5.1.1 on 2024-09-23 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_remove_case_symptoms_remove_case_treatment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='location',
        ),
        migrations.AddField(
            model_name='case',
            name='ward_district',
            field=models.CharField(choices=[('Ward 1', 'Ward 1'), ('Ward 2', 'Ward 2'), ('Ward 3', 'Ward 3'), ('Ward 4', 'Ward 4'), ('Ward 5', 'Ward 5'), ('Ward 6', 'Ward 6'), ('Ward 7', 'Ward 7'), ('Ward 8', 'Ward 8'), ('Ward 9', 'Ward 9'), ('Ward 10', 'Ward 10')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='outcome',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('Ongoing', 'Ongoing'), ('Fatal', 'Fatal')], max_length=20),
        ),
    ]
